#ifndef PINCONFIG_H
#define PINCONFIG_H

#define PIN_NUM_LEDS_MOSI         GPIO_NUM_23
#define PIN_NUM_LEDS_CLK          GPIO_NUM_18

#define PIN_NUM_DISPLAY_CS        GPIO_NUM_15
#define PIN_NUM_DISPLAY_MOSI      GPIO_NUM_13
#define PIN_NUM_DISPLAY_SCK       GPIO_NUM_14
#define PIN_NUM_DISPLAY_DATA_CMD  GPIO_NUM_27
#define PIN_NUM_DISPLAY_RESET     GPIO_NUM_26
#define PIN_NUM_DISPLAY_BACKLIGHT NOPIN
#define PIN_NUM_DISPLAY_BUSY      GPIO_NUM_34

#endif
